import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — endgit",
  description:
    "Learn how endgit collects, uses, and protects your personal data. Understand our use of GitHub OAuth, cookies, analytics, and third-party services.",
  openGraph: {
    title: "Privacy Policy — endgit",
    description:
      "Learn how endgit collects, uses, and protects your personal data. Understand our use of GitHub OAuth, cookies, analytics, and third-party services.",
    url: "https://endgit.dev/privacy",
    siteName: "endgit",
    images: [{ url: "/og-image.png", width: 1200, height: 630 }],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Privacy Policy — endgit",
    description:
      "Learn how endgit collects, uses, and protects your personal data. Understand our use of GitHub OAuth, cookies, analytics, and third-party services.",
    images: ["/og-image.png"],
  },
};

export default function PrivacyPolicyPage() {
  return (
    <div className="container py-12 md:py-20">
      <h1 className="heading-1 mb-8 text-text-primary">PRIVACY POLICY</h1>

      <div className="flex flex-col gap-6 text-text-secondary leading-relaxed">
        <p>
          This Privacy Policy describes how EndGit (&quot;we&quot;,
          &quot;us&quot;, or &quot;our&quot;) collects, uses, and protects your
          personal information when you use our website{" "}
          <a
            href="https://endgit.dev"
            className="text-accent hover:underline no-underline"
          >
            endgit.dev
          </a>{" "}
          (the &quot;Site&quot;) and related services. By using the Site, you
          agree to the collection and use of information in accordance with this
          policy.
        </p>

        <h2 className="text-xl font-semibold text-text-primary mt-4">
          INFORMATION WE COLLECT
        </h2>

        <h3 className="text-[17px] font-semibold text-text-primary mt-2">
          Account Information
        </h3>
        <p>
          When you sign in through GitHub OAuth, we collect the following
          information from your GitHub account:
        </p>
        <ul className="list-disc pl-6 flex flex-col gap-2">
          <li>GitHub username and numeric ID</li>
          <li>Display name</li>
          <li>Email address</li>
          <li>Avatar URL</li>
          <li>Bio</li>
          <li>OAuth access token and related credentials</li>
        </ul>

        <h3 className="text-[17px] font-semibold text-text-primary mt-2">
          Content You Provide
        </h3>
        <p>We collect content you voluntarily submit to the platform:</p>
        <ul className="list-disc pl-6 flex flex-col gap-2">
          <li>
            Plugin metadata: name, description, keywords, categories, license,
            repository URL, icon
          </li>
          <li>Version information: version numbers, changelogs</li>
          <li>Ratings and review comments</li>
          <li>Notes to reviewers during plugin submission</li>
          <li>Producer attribution (GitHub usernames and roles)</li>
        </ul>

        <h3 className="text-[17px] font-semibold text-text-primary mt-2">
          Automatically Collected Information
        </h3>
        <ul className="list-disc pl-6 flex flex-col gap-2">
          <li>
            IP address (used temporarily in Redis for download deduplication,
            not persisted in our database)
          </li>
          <li>
            Page views and Web Vitals metrics (via Vercel Analytics and Speed
            Insights)
          </li>
          <li>Plugin download counts and view counts (aggregated daily)</li>
          <li>CI/CD build logs and artifacts generated by the platform</li>
        </ul>

        <h2 className="text-xl font-semibold text-text-primary mt-4">
          HOW WE USE YOUR INFORMATION
        </h2>
        <p>We use the information we collect to:</p>
        <ul className="list-disc pl-6 flex flex-col gap-2">
          <li>
            Authenticate your account and manage your session via GitHub OAuth
          </li>
          <li>
            Operate and maintain the plugin marketplace, including listing,
            searching, and downloading plugins
          </li>
          <li>
            Process CI/CD builds triggered by your GitHub repositories and store
            build artifacts
          </li>
          <li>
            Send transactional email notifications about plugin approval,
            rejection, and status changes
          </li>
          <li>
            Calculate trust levels and quality scores for plugins and users to
            maintain marketplace integrity
          </li>
          <li>
            Monitor platform performance, diagnose technical issues, and prevent
            abuse through rate limiting
          </li>
          <li>
            Generate aggregate analytics for plugin downloads and page views
          </li>
        </ul>

        <h2 className="text-xl font-semibold text-text-primary mt-4">
          THIRD-PARTY SERVICES
        </h2>
        <p>
          We rely on the following third-party services to operate the platform.
          Each service has its own privacy policy governing how they handle
          data.
        </p>

        <h3 className="text-[17px] font-semibold text-text-primary mt-2">
          GitHub
        </h3>
        <p>
          We use GitHub for OAuth authentication, repository access, webhook
          integration, and CI/CD workflows. We access your GitHub profile,
          email, repositories, and organizations as authorized during the OAuth
          flow. GitHub&apos;s privacy policy applies to data held by GitHub. We
          create webhooks on your repositories only when you explicitly enable
          CI/CD for them.
        </p>

        <h3 className="text-[17px] font-semibold text-text-primary mt-2">
          Vercel
        </h3>
        <p>
          The Site is hosted on Vercel. We use Vercel Analytics to collect
          anonymized page view data and Vercel Speed Insights to collect Core
          Web Vitals performance metrics. Vercel&apos;s privacy policy governs
          the handling of data processed through their infrastructure and
          analytics services.
        </p>

        <h3 className="text-[17px] font-semibold text-text-primary mt-2">
          Cloudflare R2 (S3-Compatible Storage)
        </h3>
        <p>
          Plugin build artifacts (binary files) are stored in Cloudflare R2, an
          S3-compatible object storage service. Files are served via presigned
          URLs with a one-hour expiry. Cloudflare&apos;s privacy policy applies
          to data stored in their infrastructure.
        </p>

        <h3 className="text-[17px] font-semibold text-text-primary mt-2">
          Discord
        </h3>
        <p>
          We send automated notifications to Discord channels for operational
          events such as build completions, plugin submissions, approvals, new
          ratings, and moderation actions. No personal user data is sent to
          Discord beyond publicly visible plugin and build information.
        </p>

        <h3 className="text-[17px] font-semibold text-text-primary mt-2">
          Spacemail (Email Service)
        </h3>
        <p>
          We use Spacemail SMTP to send transactional emails to plugin authors
          regarding approval and rejection of their submissions. Emails are sent
          to the address associated with your GitHub account.
        </p>

        <h2 className="text-xl font-semibold text-text-primary mt-4">
          COOKIES AND SESSION MANAGEMENT
        </h2>
        <p>We use the following cookies and storage mechanisms:</p>
        <ul className="list-disc pl-6 flex flex-col gap-2">
          <li>
            <strong>NextAuth session cookie</strong> — A secure, HTTP-only JWT
            cookie that maintains your authenticated session. It contains your
            user ID, username, trust level, and an API token. This cookie
            expires after 7 days and is refreshed automatically.
          </li>
          <li>
            <strong>NextAuth CSRF token cookie</strong> — Used to protect
            against cross-site request forgery attacks during authentication
            flows.
          </li>
          <li>
            <strong>localStorage (theme)</strong> — We store your light/dark
            theme preference in your browser&apos;s localStorage. This data
            never leaves your device.
          </li>
        </ul>
        <p>
          We do not use third-party advertising cookies, tracking pixels, or
          cross-site tracking technologies.
        </p>

        <h2 className="text-xl font-semibold text-text-primary mt-4">
          DATA STORAGE AND SECURITY
        </h2>
        <p>
          Your data is stored in PostgreSQL (relational database) and Redis
          (session cache and job queues). We implement the following security
          measures:
        </p>
        <ul className="list-disc pl-6 flex flex-col gap-2">
          <li>
            All passwords and tokens are stored securely; OAuth tokens are
            obtained from GitHub and stored encrypted in our database
          </li>
          <li>
            JWT tokens are signed with a secret key and have a one-hour expiry
          </li>
          <li>
            Refresh tokens are stored in Redis with a 30-day TTL and are
            single-use (rotating)
          </li>
          <li>
            API rate limiting is enforced: 100 requests per 15 minutes for
            public endpoints, stricter limits for authenticated and write
            operations
          </li>
          <li>HTTPS is enforced for all communications</li>
          <li>
            Webhook signatures are verified using HMAC-SHA256 with timing-safe
            comparison
          </li>
          <li>
            Security headers are set via Helmet (Content Security Policy, etc.)
          </li>
        </ul>

        <h2 className="text-xl font-semibold text-text-primary mt-4">
          DATA RETENTION
        </h2>
        <ul className="list-disc pl-6 flex flex-col gap-2">
          <li>
            <strong>Account data</strong> — Retained as long as your account
            exists. You may request deletion at any time.
          </li>
          <li>
            <strong>Plugin data</strong> — Plugin metadata, versions, and
            associated build artifacts are retained for the lifetime of the
            plugin on the marketplace.
          </li>
          <li>
            <strong>Build logs</strong> — CI/CD build logs are retained
            indefinitely as part of the build history.
          </li>
          <li>
            <strong>Analytics</strong> — Daily aggregated download and view
            counts are retained indefinitely for historical reporting.
          </li>
          <li>
            <strong>Session tokens</strong> — JWT tokens expire after 1 hour.
            Refresh tokens expire after 30 days and are deleted on use.
          </li>
          <li>
            <strong>IP addresses</strong> — Temporarily stored in Redis for 24
            hours for download deduplication, then automatically discarded. IPs
            are never persisted to our database.
          </li>
          <li>
            <strong>Moderation logs</strong> — Audit records of administrative
            actions are retained indefinitely for accountability.
          </li>
        </ul>

        <h2 className="text-xl font-semibold text-text-primary mt-4">
          YOUR RIGHTS
        </h2>
        <p>You have the right to:</p>
        <ul className="list-disc pl-6 flex flex-col gap-2">
          <li>
            <strong>Access</strong> — Request a copy of the personal data we
            hold about you.
          </li>
          <li>
            <strong>Correction</strong> — Request correction of inaccurate
            personal data.
          </li>
          <li>
            <strong>Deletion</strong> — Request deletion of your account and
            associated personal data. Publicly submitted content (plugins,
            ratings) may be anonymized rather than deleted to maintain
            marketplace integrity.
          </li>
          <li>
            <strong>Revoke access</strong> — Revoke our GitHub App installation
            at any time through your GitHub settings, which will revoke our
            access to your repositories.
          </li>
          <li>
            <strong>Data portability</strong> — Request your data in a
            machine-readable format.
          </li>
        </ul>
        <p>
          To exercise any of these rights, contact us at{" "}
          <a
            href="mailto:two-tech-dev@proton.me"
            className="text-accent hover:underline no-underline"
          >
            two-tech-dev@proton.me
          </a>
          .
        </p>

        <h2 className="text-xl font-semibold text-text-primary mt-4">
          CHILDREN&apos;S PRIVACY
        </h2>
        <p>
          The Site is not intended for use by children under the age of 13. We
          do not knowingly collect personal information from children under 13.
          If you are a parent or guardian and believe your child has provided us
          with personal information, please contact us so we can delete it.
        </p>

        <h2 className="text-xl font-semibold text-text-primary mt-4">
          INTERNATIONAL DATA TRANSFERS
        </h2>
        <p>
          Your data may be processed and stored in servers located outside your
          country of residence. Our infrastructure providers (Vercel,
          Cloudflare) operate globally. By using the Site, you consent to the
          transfer of your data to these facilities.
        </p>

        <h2 className="text-xl font-semibold text-text-primary mt-4">
          CHANGES TO THIS POLICY
        </h2>
        <p>
          We may update this Privacy Policy from time to time. We will notify
          you of any changes by posting the new policy on this page with an
          updated &quot;last updated&quot; date. You are advised to review this
          policy periodically for any changes.
        </p>

        <h2 className="text-xl font-semibold text-text-primary mt-4">
          CONTACT US
        </h2>
        <p>
          If you have any questions about this Privacy Policy or our data
          practices, please contact us at{" "}
          <a
            href="mailto:two-tech-dev@proton.me"
            className="text-accent hover:underline no-underline"
          >
            two-tech-dev@proton.me
          </a>{" "}
          or via our{" "}
          <a
            href="https://github.com/two-tech-dev/endgit-web"
            target="_blank"
            rel="noopener noreferrer"
            className="text-accent hover:underline no-underline"
          >
            GitHub repository
          </a>
          .
        </p>

        <p className="mt-4 font-italic text-sm text-text-muted">
          Last updated: May 19, 2026
        </p>
      </div>
    </div>
  );
}
