name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

      - name: Test Build
        run: pnpm build
        env:
          NEXT_PUBLIC_API_URL: "http://localhost:4000"
          NEXT_PUBLIC_APP_URL: "https://endgit.dev"
          NEXT_PUBLIC_GITHUB_APP_INSTALL_URL: "https://github.com/apps/endgit-app/installations/new"
          NEXTAUTH_SECRET: "dummy-secret-for-build"
          NEXTAUTH_URL: "http://localhost:3000"
